languageCode = "en-us"
title = "Design Cost"
baseURL = "https://github.com/pearson-ux/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Development cost for designers."
  codePenUser = "pearson"
