languageCode = "en-us"
title = "Pearson Accessibility Guidelines"
baseURL = "https://github.com/pearson-ux/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Pearson Accessibility Guidelines**."
  codePenUser = "pearson"
